#!/usr/bin/env bash
set -euo pipefail

# This script ensures the user has the necessary local configuration files.
# It is primarily used by the installer to set up monitors.conf and permissions.
# The main config is now handled via /etc/skel and /usr/share/kwimy-hypr/.

target_root="${1:-/mnt}"
target_user="${2:-}"

if [[ -z "$target_user" ]]; then
  echo "usage: $0 <target-root> <username>" >&2
  exit 2
fi

target_home="${target_root%/}/home/$target_user"

if [[ ! -d "$target_home" ]]; then
  echo "target home not found: $target_home" >&2
  exit 1
fi

# 1. Generic Config Installer
# Iterates over all directories in /etc/skel/.config (e.g., hypr, kitty, rofi)
# and installs them to the user's home if missing.

skel_config_root="${target_root%/}/etc/skel/.config"
target_config_root="$target_home/.config"
skel_local_bin_root="${target_root%/}/etc/skel/.local/bin"
target_local_bin_root="$target_home/.local/bin"

mkdir -p "$target_config_root"

if [[ -d "$skel_config_root" ]]; then
    for item in "$skel_config_root"/*; do
        [ -e "$item" ] || continue
        item_name=$(basename "$item")
        target_path="$target_config_root/$item_name"

        # If it's a directory (like .config/kitty), use cp -rn (recursive, no-clobber)
        if [[ -d "$item" ]]; then
            if [[ ! -d "$target_path" ]]; then
                echo "Installing default config directory: $item_name"
                cp -r "$item" "$target_path"
            else
                # Directory exists, copy missing files inside it
                echo "Updating config directory: $item_name (keeping existing files)"
                cp -an "$item/." "$target_path/"
            fi
        elif [[ -f "$item" ]]; then
            # Top level file inside .config
             if [[ ! -f "$target_path" ]]; then
                echo "Installing default config file: $item_name"
                cp "$item" "$target_path"
            fi
        fi
    done
fi

if [[ -d "$skel_local_bin_root" ]]; then
    mkdir -p "$target_local_bin_root"
    for script in "$skel_local_bin_root"/*; do
        [[ -f "$script" ]] || continue
        script_name=$(basename "$script")
        target_script="$target_local_bin_root/$script_name"
        if [[ ! -f "$target_script" ]]; then
            echo "Installing local user script: $script_name"
            install -m755 "$script" "$target_script"
        fi
    done
fi

# 2. Monitors Config (Specific to Hyprland)
# We ensure the parent directory exists first
mkdir -p "$target_home/.config/hypr"
monitors_conf="$target_home/.config/hypr/monitors.conf"
if [[ ! -f "$monitors_conf" ]]; then
  printf '# Monitors configuration\n# Auto-generated by Kwimy\n# monitor=name,resolution,position,scale\n' > "$monitors_conf"
fi

# 3. Pre-seed Hypr colors to avoid first-boot variable race
kwimy_hypr_local_dir="$target_home/.local/share/kwimy/hypr"
target_colors_conf="$kwimy_hypr_local_dir/colors.conf"
fallback_colors_src="${target_root%/}/usr/share/kwimy-hypr/colors/colors.conf"
mkdir -p "$kwimy_hypr_local_dir"
if [[ ! -f "$target_colors_conf" && -f "$fallback_colors_src" ]]; then
  cp "$fallback_colors_src" "$target_colors_conf"
fi

# 4. Wallpapers
wallpapers_dir="$target_home/Pictures/Wallpapers"
mkdir -p "$wallpapers_dir"
if command -v curl >/dev/null 2>&1; then
  tmp_tar="$wallpapers_dir/Wallpapers.tar.gz"
  if curl -fsSL https://pkgs.kwimy.com/Wallpapers.tar.gz -o "$tmp_tar"; then
    if tar -xzf "$tmp_tar" -C "$wallpapers_dir" --strip-components=1; then
      rm -f "$tmp_tar"
    else
      echo "warning: failed to extract wallpapers archive" >&2
      rm -f "$tmp_tar"
    fi
  else
    echo "warning: failed to download wallpapers archive" >&2
    rm -f "$tmp_tar"
  fi
else
  echo "warning: curl not found; skipping wallpapers download" >&2
fi

# 5. Fix Permissions
# Since we might have created files as root (if running from installer), we must chown them.
uid_gid="$(awk -F: -v u="$target_user" '$1==u{print $3 ":" $4}' "$target_root/etc/passwd" || true)"

if [[ -n "$uid_gid" ]]; then
    # We chown all of .config recursively to be safe, but only if we touched things.
    # To be precise and fast, we can just chown the whole .config structure since it should belong to the user.
    if [[ -d "$target_home/.config" ]]; then
        chown -R "$uid_gid" "$target_home/.config"
    fi
    if [[ -d "$target_home/.local/share/kwimy/hypr" ]]; then
        chown -R "$uid_gid" "$target_home/.local/share/kwimy/hypr"
    fi
    if [[ -d "$target_home/.local/bin" ]]; then
        chown -R "$uid_gid" "$target_home/.local/bin"
    fi
    if [[ -d "$target_home/Pictures" ]]; then
        chown -R "$uid_gid" "$target_home/Pictures"
    fi
else
  echo "warning: user not found in $target_root/etc/passwd; ownership not updated" >&2
fi
